
language: node_js
node_js:
  - "11"

branches:
  only:
    - master
script:
  - cd backend
  - npm generate-client
  - cd ../frontend
  - npm run build

cache:
  directories:
    - backend/node_modules
    - frontend/node_modules

